    <?php

    $name=$_POST['name'];
    $pwd=$_POST['pwd'];
    $pwd1=$_POST['pwd1'];
    $em=$_POST['em'];
    $tel=$_POST['tel'];
    include("data.php");
    if(empty($name)){
    $response=[
    'error'=>10000,
    'font'=>'账号必填'
    ];
    exit(json_encode($response));
    }else{
    $name_sql="select * from fors where name='$name'";
    $name_res=mysqli_query($link,$name_sql);
    $name_info=mysqli_fetch_assoc($name_res);
    if(!empty($name_info)){
    $response=[
    'error'=>10001,
    'font'=>'该账号已被占用'
    ];
    exit(json_encode($response));
    }
    }

    if(empty($pwd)){
    $response=[
    'error'=>20000,
    'font'=>'密码必填'
    ];
    exit(json_encode($response));
    }elseif(strlen($pwd)<5){
    $response=[
    'error'=>20002,
    'font'=>'密码不低于5位'
    ];
    exit(json_encode($response));
    }elseif(empty($pwd1)){
    $response=[
    'error'=>20003,
    'font'=>'请确认密码'
    ];
    exit(json_encode($response));
    }elseif($pwd!=$pwd1){
    $response=[
    'error'=>20001,
    'font'=>'密码不一致'
    ];
    exit(json_encode($response));
    }

    if(empty($em)){
    $response=[
    'error'=>30000,
    'font'=>'邮箱必填'
    ];
    exit(json_encode($response));
    }

    if(empty($tel)){
    $response=[
    'error'=>40000,
    'font'=>'手机号必填'
    ];
    exit(json_encode($response));
    }elseif(strlen($tel)<11){
    $response=[
    'error'=>40001,
    'font'=>'手机号格式有误'
    ];
    }
    $pwd=password_hash($pwd,PASSWORD_DEFAULT);
    $time=time();
    $sql="insert into fors(name,pwd,em,tel,time)values('$name','$pwd','$em','$tel','$time')";
    $res=mysqli_query($link,$sql);
    if($res){
        $response=[
    'error'=>0,
    'font'=>'注册成功'
    ];
    exit(json_encode($response));
    }else{
    $response=[
    'error'=>1,
    'font'=>'注册失败'
    ];
    exit(json_encode($response));
    }
    ?>